---
- hosts: kube
  become: true

  pre_tasks:
    - name: Include vagrant setup fixes
      include_tasks:
        vagrant-setup.yml

  roles:
    - geerlingguy.security
    - geerlingguy.swap
    - geerlingguy.docker
    - geerlingguy.kubernetes
