---
- hosts: centos8
  become: true

  vars:
    - oracle_java_use_defaults: no
    - oracle_java_dir_source: '/usr/local/src'
    - oracle_java_download_timeout: 60
    - oracle_java_rpm_filename: 'jdk-14.0.1_linux-x64_bin.rpm'
    - oracle_java_home: '/usr/java/default'
    - oracle_java_os_supported: yes
    - oracle_java_rpm_url: 'https://download.oracle.com/otn-pub/java/jdk/14.0.1+7/664493ef4a6946b186ff29eb326336a2/jdk-14.0.1_linux-x64_bin.rpm'
    - oracle_java_rpm_validate_certs: yes
    - oracle_java_set_as_default: yes
    - oracle_java_version_string: 14.0.1
    - oracle_java_checksum: "sha256:36a7df03cac6ef62933b59b63c045d65351865421a9133d43ceb83d683a2bdff"

  roles:
    - ansiblebit.oracle-java
      #     - inkatze.wildfly
